name: GitSecretsScan

on: [push, pull_request]

jobs:
  git-secret-check:
    name: Git Secrets Scan
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/github.com/aws/amazon-ecs-agent
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          set -ex
          brew install git-secrets
          git secrets --register-aws --global
          cd $GITHUB_WORKSPACE/src/github.com/aws/amazon-ecs-agent
          git secrets --install
          git secrets --register-aws
          git secrets --scan-history
